### ISSUE TITLE
Add pull-ups resistors on MISO/MOSI of SD-Card

### ISSUE THREAD

**Issue by arabine** [GroundStudio/GroundStudio_Marble_Pico#2]
Hi,

You have made a very wondeful board. However, you should add on a future revision two pull-ups resistors on the MISO/MOSI signals of the SDCARD, 10K each.

Regards.

**Comment by victor1115** [comment]
Hello,

Thanks for your feedback.
We've studied the matter more thoroughly and decided to make this adjustment on the next revision.

Best regards.
