### ISSUE TITLE
Powering via USB and VBUS concurrently

### ISSUE THREAD

**Issue by CatalinMustata** [GroundStudio/GroundStudio_Marble_Pico#3]
Hey guys! I'm planning to use the board as a brains for a guitar effects looper and most of the time it will be powered through it's own power supply through the VBUS pin. However, when adjusting presets I foresee a case where I'll have both the USB port connected and the internal supply. Would this be a problem for the device or host?  I'm assuming not, since GND pin would be connected to both supplies, but I thought I'd double check.

**Comment by victor1115** [comment]
Hi Catalin,
On the current revision it is NOT possible to supply power via USB and VBUS concurrently.
This issue will be fixed on the next revision of the board.

**Comment by CatalinMustata** [comment]
Hey Victor,

Sorry to revive this, but I had to pause my project for a while and I only picked it up again now. I'm trying to figure out the best way to achieve automatic switching between the internal supply and USB power. 

The simplest solution I came across was to add a 5V Zener between the internal supply and VBUS - my thinking is that when USB powered VBUS will be roughly a 5V and no current would flow form my internal supply. Do you think this is a good approach? If not, I'm open to any suggestions.

Some other ideas I had were using a PNP transistor with the base connected to VBUS and VSYS connected to its collector _or_ using a logic gate to reading from my internal supply and VBUS (supply & !VBUS) and feeding VSYS.
